set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN J15 [get_ports rst]
set_property PACKAGE_PIN C17 [get_ports scl]
set_property PACKAGE_PIN D18 [get_ports sda]
set_property PACKAGE_PIN D14 [get_ports scl_1]
set_property PACKAGE_PIN F16 [get_ports sda_1]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports scl_1]
set_property IOSTANDARD LVCMOS33 [get_ports sda]

set_property IOSTANDARD LVCMOS33 [get_ports sda_1]

set_property PACKAGE_PIN V11 [get_ports led_o]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[0]}]

set_property PACKAGE_PIN U16 [get_ports {led_o[7]}]
set_property PACKAGE_PIN U17 [get_ports {led_o[6]}]
set_property PACKAGE_PIN V17 [get_ports {led_o[5]}]
set_property PACKAGE_PIN R18 [get_ports {led_o[4]}]
set_property PACKAGE_PIN N14 [get_ports {led_o[3]}]
set_property PACKAGE_PIN J13 [get_ports {led_o[2]}]
set_property PACKAGE_PIN K15 [get_ports {led_o[1]}]
set_property PACKAGE_PIN H17 [get_ports {led_o[0]}]

set_property PACKAGE_PIN E18 [get_ports valid_o_top]
set_property PACKAGE_PIN G17 [get_ports write_o]
set_property IOSTANDARD LVCMOS33 [get_ports valid_o_top]
set_property IOSTANDARD LVCMOS33 [get_ports write_o]
