set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN J15 [get_ports rst_i]
set_property IOSTANDARD LVCMOS33 [get_ports rst_i]
set_property PACKAGE_PIN D4 [get_ports tx_pin]
set_property IOSTANDARD LVCMOS33 [get_ports tx_pin]
